version: '3.8'

services:
  postgres:
    image: postgres
    container_name: alumni-postgres
    environment:
      POSTGRES_DB: alumnidb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    # volumes:
    #   - alumni-data:/var/lib/postgresql/data
    # restart: unless-stopped

volumes:
  alumni-data: